import assert from "node:assert/strict";
import { chromium } from "@playwright/test";
import { existsSync, mkdirSync } from "node:fs";

const base = process.env.VISUAL_BASE_URL || "http://127.0.0.1:5173";
mkdirSync("test-results", { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH || (existsSync("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome") ? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" : undefined) });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const page = await context.newPage();
  page.on("pageerror", (error) => errors.push(error.message));
  let geoCalls = 0;
  await page.route("**/api/iptest/geo?*", (route) => { geoCalls++; return route.fulfill({ json: { ip: "203.0.113.8", country: "HK", location: "中国香港", organization: "Example Network", provider: "IP.SB" } }); });
  await page.route("https://**/*", (route) => {
    const url = new URL(route.request().url());
    if (url.hostname === new URL(base).hostname) return route.continue();
    if (url.hostname === "challenges.cloudflare.com") return route.abort();
    if (url.pathname.startsWith("/geo/jsonp/")) return route.fulfill({ contentType: "application/javascript", body: 'routeProbeCallback("203.0.113.8", "中国香港", "AS0", "Example Network")' });
    const callback = url.searchParams.get("cb") || url.searchParams.get("callback");
    if (callback) return route.fulfill({ contentType: "application/javascript", body: `${callback}(${JSON.stringify(url.hostname.endsWith("alicdn.com") ? { content: { localIp: "203.0.113.8", ipCountry: "中国香港" } } : { ret: 0, ip: "203.0.113.8", country: "中国香港" })})` });
    const body = url.pathname.includes("cdn-cgi/trace") ? "ip=203.0.113.8\nloc=HK\n"
      : url.hostname === "ping0.cc" ? "203.0.113.8\n香港\n" : '{"ip":"203.0.113.8","country":"HK"}';
    return route.fulfill({ status: 200, contentType: "text/plain", headers: { "access-control-allow-origin": "*", "access-control-expose-headers": "cdn-user-ip", "cdn-user-ip": "203.0.113.8" }, body });
  });
  const home = await page.goto(base);
  const homePolicy = home.headers()["content-security-policy"];
  assert(homePolicy?.includes("connect-src 'self' https://challenges.cloudflare.com;"), "Run against production preview to verify CSP");
  await page.getByRole("button", { name: "提交留言", exact: true }).waitFor();
  const card = await page.locator(".feedback-form").boundingBox();
  const link = await page.getByRole("link", { name: "分流测试", exact: true }).boundingBox();
  const footer = await page.locator(".site-footer").boundingBox();
  assert(card.y + card.height < link.y && link.y + link.height < footer.y, "Footer link should be between card and company");
  await page.locator(".site-utility").scrollIntoViewIfNeeded();
  await page.screenshot({ path: "test-results/iptest-home-footer.png" });
  const navigation = page.waitForResponse((response) => response.request().isNavigationRequest() && new URL(response.url()).pathname === "/iptest");
  await page.getByRole("link", { name: "分流测试", exact: true }).click();
  assert((await navigation).headers()["content-security-policy"].includes("connect-src 'self' https:;"));
  await page.getByRole("heading", { name: "分流测试", exact: true }).waitFor();
  assert.equal(await page.locator("tbody tr").count(), 61);
  await page.getByRole("button", { name: "重新检测", exact: true }).waitFor();
  assert.equal(await page.locator(".iptest-result--ok").count(), 61);
  assert.equal(await page.locator(".iptest-organization").count(), 61);
  assert.equal(geoCalls, 1, "same exit IP must share geolocation work");
  assert.equal(await page.locator("iframe[title='出口检测']").count(), 0);
  await page.getByRole("button", { name: "AI 工具", exact: true }).click();
  assert.equal(await page.locator("tbody tr").count(), 17);
  await page.getByRole("searchbox", { name: "搜索站点或 IP" }).fill("Kimi");
  assert.equal(await page.locator("tbody tr").count(), 1);
  await page.getByRole("searchbox", { name: "搜索站点或 IP" }).fill("");
  await page.getByRole("button", { name: "开发服务", exact: true }).click();
  assert.equal(await page.locator("tbody tr").count(), 10);
  await page.getByRole("button", { name: "IP 查询", exact: true }).click();
  assert.equal(await page.locator("tbody tr").count(), 6);
  await page.getByRole("searchbox", { name: "搜索站点或 IP" }).fill("ipify");
  assert.equal(await page.locator("tbody tr").count(), 2);
  await page.getByRole("searchbox", { name: "搜索站点或 IP" }).fill("");
  await page.getByRole("button", { name: "添加站点", exact: true }).click();
  await page.getByRole("textbox", { name: "目标域名", exact: true }).fill("example.com");
  await page.getByRole("textbox", { name: "显示名称（选填）", exact: true }).fill("自定义测试");
  await page.getByRole("button", { name: "添加并检测", exact: true }).click();
  await page.getByRole("button", { name: "重测自定义测试", exact: true }).waitFor();
  await page.waitForFunction(() => !document.querySelector('[aria-label="重测自定义测试"]').disabled);
  assert.equal(await page.locator("tbody tr").count(), 1);
  await page.reload();
  await page.getByRole("button", { name: "重新检测", exact: true }).waitFor();
  await page.getByRole("button", { name: /^网站响应 / }).click();
  await page.getByRole("button", { name: "自定义", exact: true }).click();
  assert.equal(await page.locator("tbody tr").count(), 1);
  await page.getByRole("button", { name: "删除自定义测试", exact: true }).click();
  assert.equal(await page.locator("tbody tr").count(), 0);
  await page.reload();
  await page.getByRole("button", { name: "重新检测", exact: true }).waitFor();
  await page.getByRole("button", { name: "自定义", exact: true }).click();
  assert.equal(await page.locator("tbody tr").count(), 0);
  await page.getByRole("button", { name: /^出口 IP / }).click();
  await page.getByRole("button", { name: "全部", exact: true }).click();
  for (const width of [320, 375, 390, 430, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    await page.evaluate(() => window.scrollTo(0, 0));
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `overflow at ${width}`);
    await page.screenshot({ path: `test-results/iptest-${width}.png` });
    await page.getByRole("button", { name: "添加站点", exact: true }).click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `form overflow at ${width}`);
    await page.getByRole("button", { name: "取消", exact: true }).click();
  }
  await page.goto(`${base}/iptest/`);
  await page.getByRole("heading", { name: "分流测试", exact: true }).waitFor();
  const back = page.waitForResponse((response) => response.request().isNavigationRequest() && new URL(response.url()).pathname === "/");
  await page.getByRole("link", { name: "提交留言", exact: true }).click();
  assert.equal((await back).headers()["content-security-policy"], homePolicy);
  assert.deepEqual(errors, []);
  console.log("PASS: production routing/CSP, footer placement, 61 exit probes (mocked responses), sandbox JSONP, geo deduplication, filters/search, custom persistence/delete, 6 responsive widths, return navigation.");
} finally { await browser.close(); }
